- hosts: Datanode
  tasks:
  - name: Copy JDK
    copy:
      src: /root/jdk-8u171-linux-x64.rpm
      dest: /root

  - name: Copy Hadoop
    copy:
      src: /root/hadoop-1.2.1-1.x86_64.rpm
      dest: /root

  - name: Install JDK
    command: rpm -i jdk-8u171-linux-x64.rpm --force

  - name: Install Hadoop
    command: rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force
 
  - name: Create datanode directory
    file:
      path: /datanode
      state: directory

  - name: Configuring hdfs-site.xml file
    template:
      src: Datanode-hdfs-site.xml
      dest: /etc/hadoop/hdfs-site.xml

  - name: Configuring core-site.xml file
    template:
      src: Datanode-core-site.xml
      dest: /etc/hadoop/core-site.xml

  - name: permit traffic in default zone on port 9001/tcp 
    ansible.posix.firewalld:
      port: 9001/tcp
      permanent: yes
      state: enabled

  - name: Start Datanode
    command: hadoop-daemon.sh start datanode

